fastboot:
  auth:
    exclude:
      urls:
        - /
        - /**/*
        - /**/*.*
        - /auth/login
        - /auth/logout
        - /auth/verifyCode
        - /auth/userInfo
        - /auth/menuTree
        - /nas/upload
        - /nas/download
        - /nas/delete
        - /nas/batchDelete
        - /nas/spaceInfo
        - /app/appInfo
        - /app/logo
        - /commonFile/download

md5:
  salt: 5dfa5e4e11a140e2a25466edb89f8b28

